title: M3 Technology
description: The new way to create software
show_downloads: false
google_analytics:
theme: jekyll-theme-midnight
github:
  repository_url: https://github.com/m3technology
  owner_name: m3.technology
  #zip_url: http://example.com/download.zip
  #another_url: another value